AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DATABASE_URL: XXXXXXXXXX
        PRISMA_CLI_BINARY_TARGETS: rhel-openssl-1.0.x
Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: server.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /graphql
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - server.ts
        Loader:
          - .prisma=file
          - .so.node=file
        AssetNames: '[name]'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GraphqlApi:
    Description: 'API Gateway endpoint URL for Prod stage for Graphql function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/'
  GraphqlFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt GraphqlFunction.Arn
  GraphqlFunctionIamRole:
    Description: 'Implicit IAM Role created for Graphql function'
    Value: !GetAtt GraphqlFunctionRole.Arn
